### ISSUE TITLE
Forum uploads

### ISSUE THREAD

**Issue by rosariosa** [gthomas2/moodle-filter_imageopt#11]
Hi, I do not know if it's a bug: the images attached to the forums are not resized, also enabling filteruploadedfiles in the common settings it does not activate

**Comment by gthomas2** [comment]
There was an issue with forums that got fixed with the latest 3.4 and 3.5 version. What version are you using?

I believe filter uploaded files applies filters to the files themselves. This plugin is not intended to work that way.

**Comment by rosariosa** [comment]
The version is 3.5. In the pages it works very well. 
We use forum for documentation of activities, often the answers are made through attachments (documents, photos, videos) but with many answers the loading time reaches 3 minutes...
