### ISSUE TITLE
Won't filter page content image Moodle 3.8

### ISSUE THREAD

**Issue by sww-moussa** [gthomas2/moodle-filter_imageopt#13]
Hi there, new to Moodle, and found your plugin, which looks like it should do what we need for a current project. However having trouble to get it working on a 3.8 install.

For example, it doesn't seem to pick up images in a mod/page context. I've tried a little debugging and as far as I can tell the sha1 hash reference it generates in local::get_img_file() doesn't resolve to anything in the file system. I tried removing the time query string from the path, but that also doesn't seem to produce a valid reference. I've tried looking more closely at how Moodle handles these file references to troubleshoot further, but don't want to spend too much time if I'm barking up the wrong tree!

Is this plugin still maintained? And do you know if it is compatible with Moodle 3.8? Happy to look at this in earnest to try to resolve and submit a PR if useful/relevant. Would be awesome if you are able to point us in the right direction :-)

**Comment by sww-moussa** [comment]
Ok... I now see that the plugin actually works fine for images _outside_ of page content, e.g. in a topic description. Does this mean that the best route would be for us to write a component support class for pages? Similar to the one that already exists for questions?

**Comment by sww-moussa** [comment]
Have managed to fix this, although it's sort of odd :-) With pages it seems like you need to remove the time query string (as suggested above) plus force the item id number to 0.

**Comment by sww-moussa** [comment]
Fix is here - YMMV https://github.com/sww-moussa/moodle-filter_imageopt/commit/516742647ebebbd818c8c2809090bba3cf67881e

**Comment by gthomas2** [comment]
Hi sww-moussa. Thanks for the code. I'll take a look at it today. Yes I'm still maintaining it but I'm sometimes a bit slow to respond as I have a lot of work with other projects. I'll take a look at your code and leave some comments.

**Comment by gthomas2** [comment]
I've added you to the CREDITS.md file for this plugin.
I've also pushed a new MOODLE_38_STABLE branch and updated master.
I'm going to give you some time to test my fix based on your fork. I would greatly appreciate it if you could let me know if it worked OK for you. If it has then I will close this issue immediately.

**Comment by gthomas2** [comment]
closing as fixed
