### ISSUE TITLE
Quick precheck if there are some images in the text

### ISSUE THREAD

**Issue by mudrd8mz** [gthomas2/moodle-filter_imageopt#3]
In many cases including this one, as a general performance-related suggestion for filters, it is recommended to perform a quick `strpos()` check in the filtered text to see if there is potentially something to be searched for and replaced via regular expressions.

In this filter, the `filter_imageopt::filter()`  could do a quick pre-test via `strpos()` to see if there is actually some `'<img'` substring present in the text, and quit early if there is none. The `strpos()` is known to be very quick compared to regular expressions.

See other standard filters for reference.

**Comment by gthomas2** [comment]
David, thanks for your recommendation. I have committed this improvement today. I went with stripos instead of strpos so that it would cope with <IMG and <img.
