### ISSUE TITLE
Chrome wil block resources whose URLs contain both `\n` and `<` characters.

### ISSUE THREAD

**Issue by ewallah** [gthomas2/moodle-filter_imageopt#5]
When I enable the filter I get a deprecation warning in Chrome:
`Resource requests whose URLs contain raw newline characters are deprecated, and may be blocked in M60, around August 2017. Please remove newlines from places like element attribute values in order to continue loading those resources. See https://www.chromestatus.com/features/5735596811091968 for more details.`

When I disable the filter, the warning (and the filtering) is gone.

**Comment by gthomas2** [comment]
Thanks for reporting this issue. Please could I ask what version of Moodle / Chrome you are using?

**Comment by ewallah** [comment]
Latest versions:
Chrome 59.0.3071.115 (Official Build) (64-bit)
Moodle 3.3.1+ (Build: 20170714), 4b4243113f44189d9aa8e19cc040d52c84aed61e

**Comment by gthomas2** [comment]
Thanks, I've managed to replicate the issue and have fixed it. Please can you pull the latest master branch and let me know if it resolves the issue for you too.

**Comment by ewallah** [comment]
Thanks for the quick response and fix.

**Comment by gthomas2** [comment]
No worries, thanks for testing and closing. ;-)

**Comment by Brubatera** [comment]
Hello, folks!
May I ask you how did you fixed it?
I'm having a pain with this! My page can't load.
Thanks in advance.
