### ISSUE TITLE
Please update for Moodle 3.5

### ISSUE THREAD

**Issue by germanvaleroelizondo** [gthomas2/moodle-filter_imageopt#9]
Hi,

I like your image optimizer filter a lot.

We use it in our University for our high definition images of gross and microscopic pathology that we often need to show on tiny iPads for our undergraduate quizzes.

Could you please test it and upgrade it for Moodle 3.5 and update the Moodle plugins database at https://moodle.org/plugins/pluginversions.php?plugin=filter_imageopt ?

Thanks in advance.

Germán Valero,
Professor of Veterinary Pathology at FMVZ-UNAM.

**Comment by germanvaleroelizondo** [comment]
Hi Guy,

I tested your 3.5 plugin version.
It seems to be working well, but I am afraid that it does not yet comply with the new Moodle 3.5 privacy API.

Please see https://docs.moodle.org/dev/Privacy_API#Plugins_which_do_not_store_personal_data 

Please see https://docs.moodle.org/35/en/admin/tool/dataprivacy/pluginregistry 
![image optimizer does not comply with moodle privacy api]

(https://user-images.githubusercontent.com/2671923/41855427-441752e2-7858-11e8-84ba-462b6bf4771a.jpg)

**Comment by gthomas2** [comment]
@German - thanks for reminding me about the privacy stuff. I've added this to the plugin and have uploaded it to the moodle plugin DB

**Comment by germanvaleroelizondo** [comment]
Thank you Guy, for maintaining and updating this very useful plugin.
